name: Build and publish image to Docker Hub
on:
  push:
      branches:
        - master
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t gabrielumbelino/restaurante-api-product-image:latest
      - name: login to docker hub
        run:  docker login -u gabrielumbelino -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push gabrielumbelino/restaurante-api-product-image:latest